{% set name = "geomcompare" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geomcompare-{{ version }}.tar.gz
  sha256: 7e88099f531f3d8dfd293eb1ed29121ce70b214d2581ad6b33ce33b75200fdc9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=46.1.0
    - setuptools-scm >=5
    - wheel
    - pip
  run:
    - python >=3.9
    - shapely
    - pyproj
    - psycopg2
    - rtree
    - numpy

test:
  imports:
    - geomcompare
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://geomcompare.readthedocs.io/en/latest/index.html
  summary: Compare two sets of geometrical features.
  license: GPL-3.0-or-later
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - ocefpaf
